return {
	line_endings = {
		dos = "\r\n",
		unix = "\n",
		mac = "\r",
	},

	languages = {
		unspecified = 0,
		c = 1,
		clojure = 2,
		coffeescript = 3,
		cpp = 4,
		csharp = 5,
		css = 6,
		cudacpp = 7,
		dockerfile = 8,
		go = 9,
		groovy = 10,
		handlebars = 11,
		haskell = 12,
		hcl = 13,
		html = 14,
		ini = 15,
		java = 16,
		javascript = 17,
		json = 18,
		julia = 19,
		kotlin = 20,
		latex = 21,
		less = 22,
		lua = 23,
		makefile = 24,
		markdown = 25,
		objectivec = 26,
		objectivecpp = 27,
		perl = 28,
		php = 29,
		plaintext = 30,
		protobuf = 31,
		pbtxt = 32,
		python = 33,
		r = 34,
		ruby = 35,
		rust = 36,
		sass = 37,
		scala = 38,
		scss = 39,
		shell = 40,
		sql = 41,
		starlark = 42,
		swift = 43,
		tsx = 44,
		typescript = 45,
		visualbasic = 46,
		vue = 47,
		xml = 48,
		xsl = 49,
		yaml = 50,
		svelte = 51,
	},

	filetype_aliases = {
		bash = "shell",
		coffee = "coffeescript",
		cs = "csharp",
		cuda = "cudacpp",
		dosini = "ini",
		make = "makefile",
		objc = "objectivec",
		objcpp = "objectivecpp",
		proto = "protobuf",
		raku = "perl",
		sh = "shell",
		text = "plaintext",
		[""] = "plaintext",
	},
}
